spring:
  profiles: peer1
  application:
    name: Eureka-1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    #配置服务注册中心是否以自己为客户端进行注册（配置false）
    register-with-eureka: true
    #是否取得注册信息(配置false)
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8761/eureka/

---
spring:
  profiles: peer2
  application:
    name: Eureka-2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8762/eureka/

