server:
  port: 8092
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhoupeng521/testgit.git
          username: m13266804203@163.com
          password: qq123456789@
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
