server:
  port: 8888
spring:
  application:
    name: api-gateway
zuul:
  routes:
    mq-route:
      service-ip: mq-service
      path: /mq-service/**
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

